version: '3.7'
services:
  commity:
    container_name: commity
    image: cynnexis/commity
    volumes:
      - './:/root/commity'
    command: run

  test:
    container_name: commity_test
    image: cynnexis/commity
    volumes:
      - './:/root/commity'
    environment:
      - DEBUG=True
    command: test

  lint:
    container_name: commity-lint
    image: cynnexis/commity
    volumes:
      - './:/root/commity'
    command: lint